services:
  frontend:
    image: welannn/urban-ko-admin:staging
    ports:
      - "5173:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - backendnet
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  backendnet:
